site_name: SO
repo_url: https://github.com/carolbalbs/-SO-mini-shell
theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true

  features:
   - navigation.tabs

  plugins:
  - i18n:
      default_language: pt
      languages:
        pt: Português
        en: English
nav:
- Introdução : index.md     
- Explicação da Estrutura : estrutura.md 
- Chamadas ao Sistema : chamadas.md
- Demonstração mini-shell: mini-Shell.md
- Casos de uso: casos de uso.md



# utils.c - Utilitárias e Wrappers  de System Calls
# builtin.c - Implementação de Comandos Built-in
# index.c - Lógica Principal do projeto (REPL)
